services:
  # mongo:
  #   image: mongo:6.0.13-jammy
  #   # restart: always
  #   ports:
  #     - '27017:27017'
  #   volumes:
  #     - dbdata:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

  # mongo-express:
  #   image: mongo-express:1.0.2-20-alpine3.19
  #   # restart: always
  #   depends_on:
  #     - mongo
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
  #     ME_CONFIG_MONGODB_URL: ${MONGODB_URI}

  agents-service-api:
    build:
      context: .
      dockerfile: Dockerfile
    # restart: always
    # depends_on:
    #   - mongo
    ports:
      - 8000:8000
    volumes:
      - ./app/:/app:rw
    environment:
      AZURE_CLIENT_ID: ${AZURE_CLIENT_ID}
      AZURE_CLIENT_SECRET: ${AZURE_CLIENT_SECRET}
      AZURE_TENANT_ID: ${AZURE_TENANT_ID}
      AZURE_REDIRECT_URI: ${AZURE_REDIRECT_URI}
      AZURE_AUTHORITY: ${AZURE_AUTHORITY}
      QUEST_AI_SECRET_KEY: ${QUEST_AI_SECRET_KEY}
      ALGORITHM: ${ALGORITHM}
      ACCESS_TOKEN_EXPIRE_DAYS: ${ACCESS_TOKEN_EXPIRE_DAYS}



# volumes:
#   dbdata:
#     name: agents-service-mongo-db
 